### ISSUE TITLE
Disappearing duplicate datapoint

### ISSUE THREAD

**Issue by bsoule** [beeminder/BeeSwift#123]
```[tasklist]
### Desiderata
- [ ] Translate replicata from past tense to imperative tense
- [ ] Confirm we can still replicate this in v6.6
```

Bug report from a user in support today. I double checked the translogs and there was not an actual literal duplicate datapoint added to the goal, just that the iOS app was displaying duplicates.

## Replicata 

1. I recently created a do-more goal (on the 2nd of August) to practice my guitar!
2. It was created just fine, and the initial datapoint of 0 was entered there as it should have been.
3. Then I entered my first datapoint of 2 songs and then the bug occurred.

## Expectata

That it would enter my datapoint of 2 underneath the initial datapoint of 0 and that would be that.

## Resultata

It did that much, but then it re-entered a data point of 0 with the comment of "initial datapoint of 0 on the 2nd" twice.

This made it so my "history" of datapoints was:

2020-08-02 0 "initial datapoint of 0 on the 2nd"
2020-08-02 2 
2020-08-02 0 "initial datapoint of 0 on the 2nd"
2020-08-02 0 "initial datapoint of 0 on the 2nd"

I tried entering data on other goals, and nothing happened, so I don't know if it's just this one graph or maybe it's happening on lots of new iOS goals?

## Cognata

* #167
* #166

_**Verbata**: de-duping datapoints,_

**Comment by krugerk** [comment]
A first and a second attempt to reproduce this locally were unfruitful. I wonder which other items played a part in the resulting issue.

Happen again?
Internet connection?
Could it have been that the user managed to tap "Add" (data) twice fast?

**Comment by andrewpbrett** [comment]
I believe this is fixed by #167

**Comment by andrewpbrett** [comment]
User confirmed that this is still happening as of 5.7

**Comment by krugerk** [comment]
I agree. This is present in 5.7, as noted in #166. There is a fix, #167, which has not yet been made available to testers.

**Comment by chipmanaged** [comment]
Just confirming that this is still happening (and so meta-processes like meta-graphs that are run through IFTTT pick up 2, 3, or more datapoints instead of one) as of 2020-10-29, so if #167 was deployed to testers since this gissue was last updated (I think it hasn't, but just in case), it didn't solve it on my test goals.

**Comment by krugerk** [comment]
Thanks for the feedback. 
Then apparently this is another issue than the one mentioned in #166 (or the fix in #167 did not tackle the variant shown here).
The changes in #167  meant to tackle #166 was merged into master and is part of the [5.8](https://github.com/beeminder/BeeSwift/compare/5.7...5.8).

The one mentioned in #166 dealt with data that was displayed inside the beeminder ios app but not the data actually stored server side. Thus if IFTTT is picking up this bad data, then the bad data must appear on the server as well.

**Comment by theospears** [comment]
Closing as stale. Feel free to re-open if we are still seeing reports.
